app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(region = "Ontario")
app$setInputs(year = 1955)
app$snapshot()
app$setInputs(year = 1924)
app$snapshot()
app$setInputs(region = "Manitoba")
app$snapshot()
